name: test-action
run-name: Testing project workflow
on:
  push:
    branches:
      - main
jobs:
  start-project:
    name: Start project
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      DB_URL: ${{ secrets.DB_URL }}
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: yarn run start
  test-project:
    name: Test project
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: start-project 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: yarn run test
